#!/usr/bin/env python
"""
    @author Christophe Eymard <christophe.eymard@ravelsoft.com>
"""

from pwpeg.pwpeglang import toplevel
from pwpeg import Parser, SyntaxError

#####################################################

parser = Parser(toplevel)

#####################################################

if __name__ == "__main__":
    from optparse import OptionParser
    optparser = OptionParser()

    options, args = optparser.parse_args()

    for a in args:
        f = open(a, "r")
        s = f.read()
        f.close()

        try:
            adv, res = parser.partial_parse(s)
            print(res.to_python())
        except SyntaxError as e:
            import sys
            sys.stderr.write(e.complete())

